[FIX] mrp: Error on translations was fixed
After of this commit a9b692a34fcd50d7ef5f5053c61835309c33046e, returns a
traceback when overwrite the translations (Spanish by example)

The error is
ERROR: ON CONFLICT DO UPDATE command cannot affect row a
second time
HINT:  Ensure that no rows proposed for insertion within the same
command have duplicate constrained values.

And is returned because the field field_mrp_routing__location_id now
have 2 translations

closes odoo/odoo#39680

Signed-off-by: Olivier Dony (odo) <odo@openerp.com>