[FIX] stock: picking in mobile view
- Switch to mobile view
- Go to Inventory > Delivery Orders > Create
- Add an item, save & close
- Save the picking

Error: impossible to save because a mandatory field is not set.

The kanban view used in mobile should not contain the `date` field,
which is not included in the view `view_move_picking_form`. Otherwise, a
`date: false` value is sent to the server.

opw-1816837