[FIX] hw_scale: added field 'disable' to namedtuple 'ScaleProtocol'
Introduced at a852ecc926f
Getting error
TypeError: __new__() got an unexpected keyword argument 'disable'

closes odoo/odoo#28202